from _typeshed import Incomplete

full_path: Incomplete
FILES: Incomplete

def get_name(filename): ...
def get_first_name(gender: Incomplete | None = ...): ...
def get_last_name(): ...
def get_full_name(gender: Incomplete | None = ...): ...
